DROP TABLE ZZ_EVENT;

CREATE TABLE ZZ_EVENT (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT, 
  `VERSION` BIGINT(20) NOT NULL,
  `TYPE` VARCHAR(64) NOT NULL,
  `CODE` VARCHAR(64) NOT NULL,
  `KEY` BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX `KEY_UNIQUE` (`KEY` ASC)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
