CREATE TABLE ZZ_EVENT (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT, 
  `VERSION` BIGINT(20) NOT NULL,
  `EVENT_TYPE` VARCHAR(64) NOT NULL,
  `EVENT_CODE` VARCHAR(64) NOT NULL,
  `EVENT_KEY` BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX `KEY_UNIQUE` (`EVENT_KEY` ASC)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
