DROP TABLE Z_EVENTS_TO_PROCESS;
DROP TABLE Z_TASK_EVENTS_TO_PROCESS;
DROP TABLE Z_QUEUED_EVENT;
DROP TABLE Z_SUBTEAM;
DROP TABLE Z_EVENT;
DROP TABLE Z_TASK;

CREATE TABLE Z_TASK (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
  TRANSACTION_ID VARCHAR(64) NOT NULL,
  REQUEST_ID VARCHAR(64) NOT NULL,
  COUNTRY VARCHAR(64) NOT NULL,
  CREATION DATETIME NOT NULL,
  CHECKIN DATETIME NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE Z_EVENT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
  EVENT_TYPE VARCHAR(64) NOT NULL,
  CODE VARCHAR(64) NOT NULL,
  TASK_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_TASK FOREIGN KEY (TASK_ID) REFERENCES Z_TASK (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE Z_SUBTEAM (
  ID BIGINT(20) NOT NULL, 
  CODE VARCHAR(64) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE Z_QUEUED_EVENT (
  ID BIGINT(20) NOT NULL, 
  EVENT_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_QUEUE_EVENT FOREIGN KEY (EVENT_ID) REFERENCES Z_EVENT (ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE Z_TASK_EVENTS_TO_PROCESS (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
  TASK_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_TASK_EVENTS_TO_PROCESS_TASK FOREIGN KEY (TASK_ID) REFERENCES Z_TASK (ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE Z_EVENTS_TO_PROCESS (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
  EVENT_ID BIGINT(20) NOT NULL,
  TASK_EVENTS_TO_PROCESS_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_Z_EVENTS_TO_PROCESS_EVENT FOREIGN KEY (EVENT_ID) REFERENCES Z_EVENT (ID),
  CONSTRAINT FK_EVENTS_TO_PROCESS_TASK_EVENTS_TO_PROCESS_ID FOREIGN KEY (TASK_EVENTS_TO_PROCESS_ID) REFERENCES Z_TASK_EVENTS_TO_PROCESS (ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- -------------------- OLD

CREATE TABLE Z_SUBTEAM_EVENT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
  SUBTEAM_ID BIGINT(20) NOT NULL, 
  TASK_ID BIGINT(20) NOT NULL,
  EVENT_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  INDEX SUBTEAM_ID_TASK_ID_INDEX (SUBTEAM_ID, TASK_ID),
  INDEX SUBTEAM_ID_EVENT_ID_INDEX (SUBTEAM_ID, EVENT_ID),
  CONSTRAINT UQ_SUBTEAM_ID_TASK_ID_EVENT_ID UNIQUE (SUBTEAM_ID, TASK_ID, EVENT_ID),
  CONSTRAINT FK_SUBTEAM_EVENT_SUBTEAM FOREIGN KEY (SUBTEAM_ID) REFERENCES Z_SUBTEAM (ID),
  CONSTRAINT FK_SUBTEAM_EVENT_TASK FOREIGN KEY (TASK_ID) REFERENCES Z_TASK (ID),
  CONSTRAINT FK_SUBTEAM_EVENT_EVENT FOREIGN KEY (EVENT_ID) REFERENCES Z_EVENT (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE Z_EVENTS_TO_PROCESS (
  ID BIGINT(20) NOT NULL, 
  EVENT_ID BIGINT(20) NOT NULL,
  TASK_EVENTS_TO_PROCESS_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_Z_EVENTS_TO_PROCESS_EVENT FOREIGN KEY (EVENT_ID) REFERENCES Z_EVENT (ID),
  CONSTRAINT FK_EVENTS_TO_PROCESS_TASK_EVENTS_TO_PROCESS_ID FOREIGN KEY (TASK_EVENTS_TO_PROCESS_ID) REFERENCES Z_TASK_EVENTS_TO_PROCESS (ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
