package com.despegar.example.hazelcast.dto;

public enum EventType {
	CREATION, CLAIM ,PENALIZATION, SUSPENSION, DESUSPENSION, CONTACTED, NEXT_TO_BE_TAKEN, PRIORIZATE, DEPRIORIZATE, SCALATE, PREASIGNATE, RELEASE, COMPLETED
}
